# Generated by Django 2.1.7 on 2019-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    atomic = False


    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField()),
            ],
        ),
    ]
