# Generated by Django 2.1.7 on 2019-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20190214_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
