# Generated by Django 2.1.1 on 2019-02-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('core', '0004_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacoes.Avaliacao'),
        ),
    ]
