# Generated by Django 2.1.1 on 2019-02-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('endereco', '0001_initial'),
        ('core', '0005_pontoturistico_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco.Enderecos'),
            preserve_default=False,
        ),
    ]
