# Generated by Django 2.1.7 on 2019-02-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0007_auto_20190215_1152'),
        ('endereco', '0002_auto_20190215_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CEP',
            new_name='Enderecos',
        ),
    ]
